### ISSUE TITLE
How to reference?

### ISSUE THREAD

**Issue by jzdm** [tsssss/geopack#11]
Do you have any preferences on how this implementation of geopack should be referenced?

**Comment by tsssss** [comment]
Good question. Not really sure how one references a software but google tells me something like
Tian, S. (2018). The geopack and Tsyganenko models in Python (version xxx) [Software]. Available from https://pypi.org/project/geopack/.

I do suggest citing Dr. Tsyganenko's papers and Fortran codes too because he should have the credit.
