### ISSUE TITLE
Geopack says it has no attribute called geogsm, igrf_geo, etc.

### ISSUE THREAD

**Issue by RadLad2019** [tsssss/geopack#4]
Hi I'm having some problems using some of the functions in geopack, for example 

import geopack as gp 

xgsm, ygsm, zgsm = gp.geogsm(x,y,100,1)
print(xgsm,ygsm,zgsm)
 
returns module 'geopack' has no attribute 'geogsm' as well as other functions such as igrf_geo similarly saying that geopack doesn't have an attribute
I used python3 -m pip install geopack to install it, is there anything else I need to install for geopack to work.

thanks in advance.

**Comment by tsssss** [comment]
Hi there,

I've checked your code. There are several suggestions:
1. goepack depends on scipy and numpy. Please make sure they are installed.
2. Please try the following codes, which runs for me in python 3.7.3 on Mac:

Python 3.7.3 (default, Mar 27 2019, 09:23:15)

[Clang 10.0.1 (clang-1001.0.46.3)] on darwin

Type "help", "copyright", "credits" or "license" for more information.

>>> import geopack.geopack as gp

Load IGRF coefficients ...

>>> ps = gp.recalc(100)

>>> xgsm,ygsm,zgsm = gp.geogsm(2,1,100, 1)

>>> xgsm,ygsm,zgsm

(-41.00700906453125, -19.962123759781406, 89.0221254665413)

Notice the differences between the above codes and your original codes.
Remember to do recalc before any calculation. And remember to do
geopack.geopack (this is a bit confusing due to the way the package is
implemented).

Let me know if the problem persists.

Thanks,
Sheng

**Comment by RadLad2019** [comment]
Thanks so much
